/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Hugo Carreño
 */
public class FormDuracionObras extends javax.swing.JFrame {

    /**
     * Creates new form FormDatXDuracionObras
     */
    public FormDuracionObras() {
        initComponents();
        setTitle("REGISTRO CONTRATO LABORAL X DURACION DE OBRA");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NULL = new javax.swing.JLabel();
        lbINGRESO = new javax.swing.JLabel();
        lbCONTRATO = new javax.swing.JLabel();
        lbPENSIONES = new javax.swing.JLabel();
        lbARL = new javax.swing.JLabel();
        lbCOLOR = new javax.swing.JLabel();
        lbCURSOS = new javax.swing.JLabel();
        lbCERTIFICACION = new javax.swing.JLabel();
        lbDOCUMENTO = new javax.swing.JLabel();
        lbLABORES = new javax.swing.JLabel();
        lbBASICO = new javax.swing.JLabel();
        lbTRANSPORTE = new javax.swing.JLabel();
        lbCUENTA = new javax.swing.JLabel();
        lbPAGO = new javax.swing.JLabel();
        lbMOTO = new javax.swing.JLabel();
        lbMARCA = new javax.swing.JLabel();
        lbASEGURADORA = new javax.swing.JLabel();
        lbCARGO = new javax.swing.JLabel();
        txtCONTRATO = new javax.swing.JTextField();
        cbxMOTO = new javax.swing.JComboBox();
        cbxMODELO = new javax.swing.JComboBox();
        txtCARGO = new javax.swing.JComboBox();
        txtBASICO = new javax.swing.JTextField();
        txtTRANSPORTE = new javax.swing.JTextField();
        cbxLABORES = new javax.swing.JComboBox();
        cbxCUENTA = new javax.swing.JComboBox();
        cbxPAGO = new javax.swing.JComboBox();
        cbxPENSIONES = new javax.swing.JComboBox();
        cbxCURSOS = new javax.swing.JComboBox();
        txtCOLOR = new javax.swing.JTextField();
        cbxARL = new javax.swing.JComboBox();
        cbxMARCA = new javax.swing.JComboBox();
        cbxASEGURADORA = new javax.swing.JComboBox();
        lbTCONTRATO = new javax.swing.JLabel();
        lbMODELO = new javax.swing.JLabel();
        lbCIUDAD = new javax.swing.JLabel();
        lbNDOCUMENTO = new javax.swing.JLabel();
        lbTCARGO = new javax.swing.JLabel();
        lbMOVILIDAD = new javax.swing.JLabel();
        lbBCUENTA = new javax.swing.JLabel();
        lbNCUENTA = new javax.swing.JLabel();
        lbINSTITUCION = new javax.swing.JLabel();
        lbCOMPENSACION = new javax.swing.JLabel();
        lbATEP = new javax.swing.JLabel();
        cbxDOCUMENTO = new javax.swing.JComboBox();
        cbxTCONTRATO = new javax.swing.JComboBox();
        cbxTCARGO = new javax.swing.JComboBox();
        cbxBCUENTA = new javax.swing.JComboBox();
        cbxSALUD = new javax.swing.JComboBox();
        txtINSTITUACION = new javax.swing.JTextField();
        txtDOCUMENTO = new javax.swing.JTextField();
        txtMOVILIDAD = new javax.swing.JTextField();
        cbxCIUDAD = new javax.swing.JComboBox();
        txtNCUENTA = new javax.swing.JTextField();
        txtPLACAS = new javax.swing.JTextField();
        txtNPLACAS = new javax.swing.JTextField();
        lbRETIRO = new javax.swing.JLabel();
        cbxSOAT = new javax.swing.JComboBox();
        lbSALUD = new javax.swing.JLabel();
        txtATEP = new javax.swing.JTextField();
        lbCILINDRAJE = new javax.swing.JLabel();
        lbSOAT = new javax.swing.JLabel();
        lbVENCIMIENTO = new javax.swing.JLabel();
        txtCILINDRAJE = new javax.swing.JTextField();
        cbxCOMPENSACION = new javax.swing.JComboBox();
        lbVENCIMIENTO2 = new javax.swing.JLabel();
        btELIMINAR = new javax.swing.JButton();
        btMODIFICAR = new javax.swing.JButton();
        btBUSCAR = new javax.swing.JButton();
        btGUARDAR = new javax.swing.JButton();
        dtVENCIMIENTO = new datechooser.beans.DateChooserCombo();
        dtINGRESO = new datechooser.beans.DateChooserCombo();
        dtRETIRO = new datechooser.beans.DateChooserCombo();
        dtVENCIMIENTO2 = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateChooserCombo5 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NULL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NULL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NULL.setText("DATOS DEL CONTRATO X DURACION DE OBRA");
        jPanel1.add(NULL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 580, -1));

        lbINGRESO.setText("FECHA DE INGRESO");
        jPanel1.add(lbINGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 140, 20));

        lbCONTRATO.setText("No DE CONTRATO");
        jPanel1.add(lbCONTRATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 20));

        lbPENSIONES.setText("FONDO DE PENSIONES");
        jPanel1.add(lbPENSIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 20));

        lbARL.setText("ARL");
        jPanel1.add(lbARL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 20));

        lbCOLOR.setText("COLOR");
        jPanel1.add(lbCOLOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 20));

        lbCURSOS.setText("LISTADO DE CURSOS");
        jPanel1.add(lbCURSOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 20));

        lbCERTIFICACION.setText("FECHA DE CERTIFICACION");
        jPanel1.add(lbCERTIFICACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 140, 20));

        lbDOCUMENTO.setText("TIPO DE DOCUMENTO");
        jPanel1.add(lbDOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 140, 20));

        lbLABORES.setText("ZONA DE LABORES");
        jPanel1.add(lbLABORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 20));

        lbBASICO.setText("SALARIO BASICO");
        jPanel1.add(lbBASICO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 140, 20));

        lbTRANSPORTE.setText("AUXILIO DE TRANSPORTE");
        jPanel1.add(lbTRANSPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 20));

        lbCUENTA.setText("TIPO DE CUENTA");
        jPanel1.add(lbCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 20));

        lbPAGO.setText("PERIODO DE PAGO");
        jPanel1.add(lbPAGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 20));

        lbMOTO.setText("MOTOCICLETA");
        jPanel1.add(lbMOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 20));

        lbMARCA.setText("MARCA");
        jPanel1.add(lbMARCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 140, 20));

        lbASEGURADORA.setText("ASEGURADORA");
        jPanel1.add(lbASEGURADORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 140, 20));

        lbCARGO.setText("CARGO");
        jPanel1.add(lbCARGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, 20));
        jPanel1.add(txtCONTRATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 130, -1));

        jPanel1.add(cbxMOTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 40, -1));

        jPanel1.add(cbxMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 80, -1));

        jPanel1.add(txtCARGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 130, -1));

        txtBASICO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBASICO.setText("$");
        jPanel1.add(txtBASICO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 130, -1));

        txtTRANSPORTE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTRANSPORTE.setText("$");
        jPanel1.add(txtTRANSPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, -1));

        jPanel1.add(cbxLABORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 130, -1));

        jPanel1.add(cbxCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, -1));

        jPanel1.add(cbxPAGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 130, -1));

        jPanel1.add(cbxPENSIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, -1));

        jPanel1.add(cbxCURSOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 80, -1));

        txtCOLOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCOLOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 130, -1));

        jPanel1.add(cbxARL, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 130, -1));

        jPanel1.add(cbxMARCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, -1));

        jPanel1.add(cbxASEGURADORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 130, -1));

        lbTCONTRATO.setText("TIPO DE CONTRATO");
        jPanel1.add(lbTCONTRATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 140, 20));

        lbMODELO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMODELO.setText("MODELO");
        jPanel1.add(lbMODELO, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 70, 20));

        lbCIUDAD.setText("CIUDAD");
        jPanel1.add(lbCIUDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 140, 20));

        lbNDOCUMENTO.setText("# DE DOCUMENTO");
        jPanel1.add(lbNDOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 140, 20));

        lbTCARGO.setText("TIPO DE CARGO");
        jPanel1.add(lbTCARGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 140, 20));

        lbMOVILIDAD.setText("AUXILIO MOVILIDAD");
        jPanel1.add(lbMOVILIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 140, 20));

        lbBCUENTA.setText("BANCO CUENTA");
        jPanel1.add(lbBCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, 20));

        lbNCUENTA.setText("NUMERO DE CUENTA");
        jPanel1.add(lbNCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 20));

        lbINSTITUCION.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbINSTITUCION.setText("INSTITUCION");
        jPanel1.add(lbINSTITUCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 100, 20));

        lbCOMPENSACION.setText("CAJA COMPENSACION");
        jPanel1.add(lbCOMPENSACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 140, 20));

        lbATEP.setText("% ATEP");
        jPanel1.add(lbATEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 140, 20));

        cbxDOCUMENTO.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECCIONE...", "CEDULA DE CIUDADANIA", "TARJETA DE IDENTIDAD", "CEDULA DE EXTRANGERIA" }));
        jPanel1.add(cbxDOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 130, -1));

        cbxTCONTRATO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTCONTRATOActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTCONTRATO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 130, -1));

        jPanel1.add(cbxTCARGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 130, -1));

        jPanel1.add(cbxBCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 130, -1));

        jPanel1.add(cbxSALUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 130, -1));
        jPanel1.add(txtINSTITUACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 220, -1));
        jPanel1.add(txtDOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 130, -1));
        jPanel1.add(txtMOVILIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 130, -1));

        jPanel1.add(cbxCIUDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 130, -1));
        jPanel1.add(txtNCUENTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 130, -1));

        txtPLACAS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPLACAS.setText("PLACAS");
        jPanel1.add(txtPLACAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 80, -1));

        txtNPLACAS.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNPLACAS.setText("# PLACAS");
        jPanel1.add(txtNPLACAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 80, -1));

        lbRETIRO.setText("FECHA DE RETIRO");
        jPanel1.add(lbRETIRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 140, 20));

        jPanel1.add(cbxSOAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 130, -1));

        lbSALUD.setText("FONDO DE SALUD");
        jPanel1.add(lbSALUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 140, 20));
        jPanel1.add(txtATEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 130, -1));

        lbCILINDRAJE.setText("CILINDRAJE");
        jPanel1.add(lbCILINDRAJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 140, 20));

        lbSOAT.setText("SOAT");
        jPanel1.add(lbSOAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, 20));

        lbVENCIMIENTO.setText("FECHA DE VENCIMIENTO");
        jPanel1.add(lbVENCIMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 140, 20));
        jPanel1.add(txtCILINDRAJE, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 130, -1));

        jPanel1.add(cbxCOMPENSACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 130, -1));

        lbVENCIMIENTO2.setText("FECHA DE VENCIMIENTO");
        jPanel1.add(lbVENCIMIENTO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 20));

        btELIMINAR.setText("ELIMINAR");
        jPanel1.add(btELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        btMODIFICAR.setText("GUARDAR");
        jPanel1.add(btMODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        btBUSCAR.setText("BUSCAR");
        jPanel1.add(btBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));

        btGUARDAR.setText("MODIFICAR");
        jPanel1.add(btGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));
        jPanel1.add(dtVENCIMIENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 130, -1));
        jPanel1.add(dtINGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 130, -1));
        jPanel1.add(dtRETIRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 130, -1));
        jPanel1.add(dtVENCIMIENTO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 32, 32));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 32, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 32, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, 32, 32));
        jPanel1.add(dateChooserCombo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxTCONTRATOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTCONTRATOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTCONTRATOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDuracionObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDuracionObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDuracionObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDuracionObras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDuracionObras().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NULL;
    private javax.swing.JButton btBUSCAR;
    private javax.swing.JButton btELIMINAR;
    private javax.swing.JButton btGUARDAR;
    private javax.swing.JButton btMODIFICAR;
    private javax.swing.JComboBox cbxARL;
    private javax.swing.JComboBox cbxASEGURADORA;
    private javax.swing.JComboBox cbxBCUENTA;
    private javax.swing.JComboBox cbxCIUDAD;
    private javax.swing.JComboBox cbxCOMPENSACION;
    private javax.swing.JComboBox cbxCUENTA;
    private javax.swing.JComboBox cbxCURSOS;
    private javax.swing.JComboBox cbxDOCUMENTO;
    private javax.swing.JComboBox cbxLABORES;
    private javax.swing.JComboBox cbxMARCA;
    private javax.swing.JComboBox cbxMODELO;
    private javax.swing.JComboBox cbxMOTO;
    private javax.swing.JComboBox cbxPAGO;
    private javax.swing.JComboBox cbxPENSIONES;
    private javax.swing.JComboBox cbxSALUD;
    private javax.swing.JComboBox cbxSOAT;
    private javax.swing.JComboBox cbxTCARGO;
    private javax.swing.JComboBox cbxTCONTRATO;
    private datechooser.beans.DateChooserCombo dateChooserCombo5;
    private datechooser.beans.DateChooserCombo dtINGRESO;
    private datechooser.beans.DateChooserCombo dtRETIRO;
    private datechooser.beans.DateChooserCombo dtVENCIMIENTO;
    private datechooser.beans.DateChooserCombo dtVENCIMIENTO2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbARL;
    private javax.swing.JLabel lbASEGURADORA;
    private javax.swing.JLabel lbATEP;
    private javax.swing.JLabel lbBASICO;
    private javax.swing.JLabel lbBCUENTA;
    private javax.swing.JLabel lbCARGO;
    private javax.swing.JLabel lbCERTIFICACION;
    private javax.swing.JLabel lbCILINDRAJE;
    private javax.swing.JLabel lbCIUDAD;
    private javax.swing.JLabel lbCOLOR;
    private javax.swing.JLabel lbCOMPENSACION;
    private javax.swing.JLabel lbCONTRATO;
    private javax.swing.JLabel lbCUENTA;
    private javax.swing.JLabel lbCURSOS;
    private javax.swing.JLabel lbDOCUMENTO;
    private javax.swing.JLabel lbINGRESO;
    private javax.swing.JLabel lbINSTITUCION;
    private javax.swing.JLabel lbLABORES;
    private javax.swing.JLabel lbMARCA;
    private javax.swing.JLabel lbMODELO;
    private javax.swing.JLabel lbMOTO;
    private javax.swing.JLabel lbMOVILIDAD;
    private javax.swing.JLabel lbNCUENTA;
    private javax.swing.JLabel lbNDOCUMENTO;
    private javax.swing.JLabel lbPAGO;
    private javax.swing.JLabel lbPENSIONES;
    private javax.swing.JLabel lbRETIRO;
    private javax.swing.JLabel lbSALUD;
    private javax.swing.JLabel lbSOAT;
    private javax.swing.JLabel lbTCARGO;
    private javax.swing.JLabel lbTCONTRATO;
    private javax.swing.JLabel lbTRANSPORTE;
    private javax.swing.JLabel lbVENCIMIENTO;
    private javax.swing.JLabel lbVENCIMIENTO2;
    private javax.swing.JTextField txtATEP;
    private javax.swing.JTextField txtBASICO;
    private javax.swing.JComboBox txtCARGO;
    private javax.swing.JTextField txtCILINDRAJE;
    private javax.swing.JTextField txtCOLOR;
    private javax.swing.JTextField txtCONTRATO;
    private javax.swing.JTextField txtDOCUMENTO;
    private javax.swing.JTextField txtINSTITUACION;
    private javax.swing.JTextField txtMOVILIDAD;
    private javax.swing.JTextField txtNCUENTA;
    private javax.swing.JTextField txtNPLACAS;
    private javax.swing.JTextField txtPLACAS;
    private javax.swing.JTextField txtTRANSPORTE;
    // End of variables declaration//GEN-END:variables
}
